### ISSUE TITLE
PHPCS

### ISSUE THREAD

**Issue by nasyrov** [jjgrainger/PostTypes#1]
Hi there,

Thanks for the great plugin!

I was thinking, it would be nice if you can integrate PHP CodeSniffer and lint your code against PSR2 code stylings...

Thanks,
E

**Comment by inasyrov** [comment]
PS: If you are ok with that, I can submit a PR with the PHPCS and travis integration.

**Comment by jjgrainger** [comment]
@nasyrov Yes, that would be great thank you!
