### ISSUE TITLE
Automatic post type names by slug not working on v1.1.1

### ISSUE THREAD

**Issue by Rodenastyle** [jjgrainger/PostTypes#10]
Post type name, singular, and plural are not generated automatically from slug on CPT creation.
This has happened after updating to the last release v1.1.1.

I've solved it by forcing the version 1.0 on the composer.json.

Best regards,

**Comment by jjgrainger** [comment]
Hi @Rodenastyle,

Everything seems to be working fine for me. Could you provide a bit more detail, including code so I can try and recreate the issue.

Thanks :)

**Comment by jjgrainger** [comment]
Hi @Rodenastyle,

I'm going to assume this is fixed now in version 2 and above, so I am closing the issue.

If not, please create a new issue and provide any details and code examples so I can recreate the issue and I'll try help where I can.

Thanks :)
