### ISSUE TITLE
Conflict with WooCommerce admin columns

### ISSUE THREAD

**Issue by indrek-k** [jjgrainger/PostTypes#12]
Using PostTypes on WooCommerce 'product' post type seems to create duplicate Product Category and Product Type admin column values.

**Repro:**
1. Install WooCommerce
2. Import dummy data
3. new PostType('product');
4. Have a look at the Products admin table

**Expected result:**
![admincols2](https://user-images.githubusercontent.com/1229164/27481241-51fc8b34-5824-11e7-95c3-cf7109a6b2b5.PNG)

**Actual result:**
![admincols](https://user-images.githubusercontent.com/1229164/27481175-ee03534c-5823-11e7-8589-28c61cd73a3d.PNG)

**Workaround:**
```
<?php

    $product->columns()->populate('product_cat', function() {
       // do nothing
    });

    $product->columns()->populate('product_type', function() {
        // do nothing
    });
```

I'm pretty sure this doesn't really qualify as a 'bug'. However, it took me a while to figure out what's going on while developing a bigger ecommerce site. Could we perhaps add a note to the documentation about this?

Thanks for this excellent library!

**Comment by jjgrainger** [comment]
@indrek-k Thanks for this, I will investigate :)

**Comment by jjgrainger** [comment]
I think this is related to #13
