### ISSUE TITLE
taxonomy - show_admin_column

### ISSUE THREAD

**Issue by mmjaeger** [jjgrainger/PostTypes#13]
<img width="1182" alt="screen shot 2017-06-29 at 2 08 08 pm" src="https://user-images.githubusercontent.com/1554580/27736050-426a3fa8-5d57-11e7-94d6-8e01943b93d4.png">
using "show_admin_column" as an option when creating a taxonomy I'm getting duplicate columns in the WP admin - see screenshot.

**Comment by jjgrainger** [comment]
@mmjaeger Thanks for this,

This will be down to PostTypes not taking the `show_admin_column` option into consideration. So when the columns are generated by both WordPress and PostTypes.

I'll fix this.

**Comment by jjgrainger** [comment]
@mmjaeger This has been fixed now in v2.0.

PostTypes now makes use of `show_admin_column` option for displaying taxonomy columns and no longer does this manually.
