### ISSUE TITLE
Sorting not working

### ISSUE THREAD

**Issue by seldimi** [jjgrainger/PostTypes#15]
Hey. I have issues with sorting. I am using ACF to create custom fields. Even columns populate correctly, it has ASC sorting, even if I see &order=desc.
As for text, it doesn't order correctly.

Part of code 
```
        $portfolio->columns()->set([
            'cb' => '<input type="checkbox" />',
            'title' => __("Title"),
            'port_tax' => __("Categories"),
            'port_tag' => __("Tags"),
            'client' => __("Client"),
            'sort_order' => __("Sort Order"),
            'date' => __("Date")
        ]);

        $portfolio->columns()->populate('client', function($column, $post_id) {
            $client=get_field('client_related',$post_id);
            echo (isset($client[0]) ? $client[0]->post_title : '');
        });

        $portfolio->columns()->populate('sort_order', function($column, $post_id) {
            $sort_order=get_post_meta($post_id,'sort_order',true);
            echo (int)(isset($sort_order) ? $sort_order : 999999999999);
        });

        $portfolio->columns()->sortable([
            'sort_order' => ['sort_order', true],
            'client' => ['client', false],
        ]);
```

**Comment by jjgrainger** [comment]
Hi @seldimi,

WordPress uses the values stored in the database to set the sort order. So for the `client` column, it won't use the `$client[0]->post_title` to order it.

I imagine you are using an [ACF relationship](https://www.advancedcustomfields.com/resources/relationship/) field for the `client_related` field. If so, the value will be saved in the database as a serialized array, which cannot be sorted (sa far as I'm aware).

I'll do some research myself, but if you come across a solutions I'll be interested to know.

As for the `sort_order` column, I've noticed WordPress will struggle to order items that don't have the meta field saved against the post. So if any of your posts do not have a `sort_order` meta associated with it, the ordering can look wrong.

I hope that helps,

Thanks :)

**Comment by seldimi** [comment]
Yes its a relation field... so you tell me that wordpress sees something like {3:5} so it cannot sort it correctly?

As for the sort_order, I did not get it.. I have set sort_order to every custom post type, but still doesn't work well. But it does read its value, isnt it ?

**Comment by jjgrainger** [comment]
Yes @seldimi, that is correct.

WordPress will see the serialized value like `{"3":"123"}` so it cannot be sorted correctly.

As for the `sort_order` I would have thought it would work. Could you provide me with the full code and let me know what type of field you are using for the `sort_order` meta. Then I'll take a look and see if I can work out what's happening.

Thanks :)

**Comment by jjgrainger** [comment]
Closing this issue out as it's now stale.
