### ISSUE TITLE
Not translating default labels

### ISSUE THREAD

**Issue by seldimi** [jjgrainger/PostTypes#16]
I have also noticed another thing. Without declaring any textdomains, the labels are not translated to my native language (Greek) but are in English. It doesnt trigger WordPress native language file. 
Only those who are handwritten are translated.

**Comment by jjgrainger** [comment]
Hi @seldimi,

I believe this has something to do with execution order where labels are being generated too soon (see [this comment](https://github.com/jjgrainger/PostTypes/issues/2#issuecomment-304739466) on issue #2)

I'm working to fix this with v2.0.

**Comment by seldimi** [comment]
Pefect! I really loved your PostTypes and use it almost anywhere.
Really keen on seeing the v2

**Comment by jjgrainger** [comment]
@seldimi This has been fixed in v2, details can be found in the pull request (#18)
