### ISSUE TITLE
Add full documentation

### ISSUE THREAD

**Issue by jjgrainger** [jjgrainger/PostTypes#17]
After the changes made for v2.0 using a single README for documentation just won't do!

Create a small Jekyll blog in `/docs` folder of the project, hosted with Github Pages.

**Comment by dsasko** [comment]
In the "Create new taxonomy" section, mention that the taxonomy class also needs to be loaded before use.

`use PostTypes\Taxonomy;`

**Comment by jjgrainger** [comment]
Potentially looking at [GitBook](https://www.gitbook.com/) now...

**Comment by JoshuaCrewe** [comment]
Until the git book is done #26 will fix what @dsasko was talking about. #EveryLittleHelps
