### ISSUE TITLE
Ultimate proofing

### ISSUE THREAD

**Issue by noplanman** [jjgrainger/PostTypes#32]
To be a good boy and create an issue before the PR (even though I've already started work on this :grin:)

Basically, I've proofread the entire documentation and will create different PRs that bundle certain changes (like `typos`, `grammar`, `code examples`, etc.) to make it easier to work through.

As I make PRs, I'll list them here to keep everything sane.

Best work through these in order, so that rebasing / merging is easier :+1:
- Copy-paste fixes (PR #33)
- Fix typos and spelling mistakes (PR #34)
- Various grammar and wording corrections. (PR #35)
- Improve code examples (PR #36)
- Various touch ups (PR #37)

**Comment by noplanman** [comment]
@jjgrainger Ok, have done my proofing :tada: 

Take a look and let me know if you want any changes or anything.

:exclamation: Note: As the PRs are completely separate, I (or you if you want to) will need to rebase / merge after each one.

**Comment by jjgrainger** [comment]
@noplanman Thank you, this is great work! 👍 

I'm going to try and dedicate some time today/tomorrow to review and merge each of them.

**Comment by jjgrainger** [comment]
@noplanman All PRs have been merged! 🎉 

Thanks again for all your work on this, truly awesome!

**Comment by noplanman** [comment]
@jjgrainger You're so welcome :innocent: 

Will do the 100% WP Coding Standards when I next have a moment :+1:
