### ISSUE TITLE
WP Coding standards

### ISSUE THREAD

**Issue by noplanman** [jjgrainger/PostTypes#42]
Not really a bug, but shouldn't the whole PHP code follow strict WP Coding Standards too?

@jjgrainger Obviously feel free to just close this off if you prefer to keep your style, this is more of a suggestion, as it's a pure WordPress project.

**Comment by jjgrainger** [comment]
Thanks for the issue.

I chose to go with the [PSR-2](https://www.php-fig.org/psr/psr-2/) standards to keep this project inline with modern PHP practices.

Based on the reactions from others, I think we'll keep this code style for now.

Thanks again :)
