### ISSUE TITLE
Custom Post not showing in wordpress search.

### ISSUE THREAD

**Issue by tompha** [jjgrainger/PostTypes#44]
I have registered my post type as follows and would expect to see it display in the standard search loop.

`
$recipes = new PostType([
    'name' => 'recipes',
    'singular' => 'Recipe',
    'plural' => 'Recipes',
    'slug' => 'recipes',
], [
    'supports' => ['title', 'excerpt', 'revisions', 'thumbnail'],
    'has_archive' => true,
    'menu_icon' => 'dashicons-carrot',
    'public'             => true,
    'publicly_queryable' => true,
    'exclude_from_search' => false,
    'capability_type' => 'post',
    'query_var' => true,
    'show_in_menu' => true
]);
`

Unfortunately, when I search for one of my recipes it doesn't show in my list. All other post types are showing. Is this a bug you have run into before?

**Comment by polishedwp** [comment]
@tompha This is normal for CPT. You have to add the CPT to the WP query. Look here for one example of how to fix: 
https://thomasgriffin.io/how-to-include-custom-post-types-in-wordpress-search-results/

**Comment by jjgrainger** [comment]
@tompha I have tested this with WordPress 5.4 and have found custom post types to show in the standard search with the options you supplied.

I'm going to close the issue out as I cannot recreate the issue, but please feel free to reopen/raise a new issue if the problem persists.

Thanks!
