### ISSUE TITLE
populate column for taxonomy not working

### ISSUE THREAD

**Issue by mmjaeger** [jjgrainger/PostTypes#47]
hello
got the following code:

`$cats = new Taxonomy( $names, $options );
	$cats->posttype( 'gear' );
	
	$cats->columns()->add( array(
		'pid' => __( 'ID' ),
	) );
	
	$cats->columns()->populate( 'pid', function ( $column, $post_id ) {
		
		var_dump($post_id); // this shows 'pid' instead of the $post_id
	} );
	
	$cats->columns()->order( array(
		'pid' => 1
	) );`

trying to populate the pid column with the taxonomy ID but $post_id returns 'pid'??

what am I missing??

**Comment by mmjaeger** [comment]
figured it out - functions has a third param - this works:
`$cats->columns()->populate( 'pid', function ( $content, $column, $term_id ) {
		echo $term_id;
	} );`

**Comment by jjgrainger** [comment]
@mmjaeger Yes, the filter for term columns is slightly different to the way it works for post types.

As you figured out, It passes 3 parameters to the function - `$content`, `$column_name` and `$term_id`.

I will need to update the documentation to make this clearer.

Thanks 👍
