### ISSUE TITLE
Submitbox edit

### ISSUE THREAD

**Issue by LeninZapata** [jjgrainger/PostTypes#49]
Hi, it is possible to edit the submitbox ?
![image](https://user-images.githubusercontent.com/42600954/55937707-442b7e80-5bff-11e9-8fb2-adafb58a20e5.png)

**Comment by jjgrainger** [comment]
Hi @LeninZapata, thank you for your patience.

At the moment there is not way to modify the submit box using PostTypes and I don't plan to add this as a feature with Gutenberg is part of WordPress now.

You can look into using the [`post_submitbox_misc_actions`](https://codex.wordpress.org/Plugin_API/Action_Reference/post_submitbox_misc_actions) action to make changes to the submitbox.

Thanks
