### ISSUE TITLE
Add column to POST

### ISSUE THREAD

**Issue by LeninZapata** [jjgrainger/PostTypes#51]
Hello, can I add columns to the POST type of the wordpress core? 
I'm trying this but I have no results
```
$postcolumn = new PostType('post');
$postcolumn->columns()->add([
    'shortcode'  => __('Shortcode', 'tx' ),
]);
```

**Comment by jjgrainger** [comment]
Hi @LeninZapata 

Based on your code it looks like you need to register the changes to WordPress with the register() method like so:

```php
$postcolumn = new PostType('post');

$postcolumn->columns()->add([
    'shortcode'  => __('Shortcode', 'tx' ),
]);

// Register the changes...
$postcolumn->register();
```

Let me know if this works for you :)

**Comment by LeninZapata** [comment]
It worked! thank you
