### ISSUE TITLE
Taxonomies do not display when using Gutenberg Editor

### ISSUE THREAD

**Issue by csaborio001** [jjgrainger/PostTypes#53]
WordPress: 5.2.2
PHP:  7.2.8

In order to make the CPT display the Gutenberg editor, I set the option as follows:

`    // Create a books Post Type
    $books = new PostType('book');
    $books->options( array (
        **'show_in_rest'      => true,**
    ));`

(this is the only change I make yo your books.php file)

With only this change, the taxonomy does not display:

https://drive.google.com/open?id=1oJ9paXGHN-8xO39vEoweAZZwXydgK0Gx

I'll try and debug when I get a chance.

**Comment by jjgrainger** [comment]
Hi @csaborio001 

The [`register_taxonomy`](https://developer.wordpress.org/reference/functions/register_taxonomy/) function has the same `show_in_rest` option as post types.

If you update the Genres options to include `'show_in_rest' => true` this should make the taxonomy appear in the Gutenberg editor.

Let me know if that fixes things,

Thanks :)

**Comment by csaborio001** [comment]
Thank **you** for creating this code!

I realised that as soon as I submitted the bug, but the taxonomy still does not show when adding/editing the post. But maybe I just need a break, I'll try again tomorrow.

`$options = array(
    'show_in_rest'      => true,
);

// Create a books Post Type
$books = new PostType('book', $options);

// Add the Genre Taxonomy
$books->taxonomy('genre', $options );`

**Comment by csaborio001** [comment]
Hmmm...I just started a new project and [did work out of the box](https://drive.google.com/open?id=1Fyp9Vq0xpSA6WwcbajbPaeHIol4eyFX8), so closing this up!

Thanks again for creating this project!
