### ISSUE TITLE
Sorting broken when column key and orderby column do not match

### ISSUE THREAD

**Issue by bookwyrm** [jjgrainger/PostTypes#54]
I have added a new column `event_date` to an `Event` CPT and I want to sort on that column. The actual "event date" can be either a single day (`start_date`) or a range with a start and and end date (`end_date`). I want the column to be sortable by the "event date" so I setup the sort to use the underlying `start_date` according to the documentation:

```php
$events->columns()->sortable([
	'event_date' => [ 'start_date', $sort_number ],
]);
```

This adds the column to the admin interface and makes it sortable and WordPress (5.2.3) sets the `orderby` query param to `start_date` which is the actual underlying post meta field that I want to sort by. 

I'm encountering an issue in the `setSortableColumn` function of the `PostTypes\PostType` class. In that function, it checks if the `orderby` param (`start_date` in my case) is setup as a sortable column. This check fails because my "sortable column" is `event_date` and the DB query never gets modified to actually implement the sort.

**Comment by jjgrainger** [comment]
Thank you for raising the issue and PR.
