### ISSUE TITLE
Internationalize the dropdown list of taxonomies

### ISSUE THREAD

**Issue by JoaoBrlt** [jjgrainger/PostTypes#66]
Hi @jjgrainger 

Firstly, thank you for this small library that really helps to simplify the code of my WordPress plugins ! 

The issue I'm pointing out is that the default label of the dropdown list of taxonomies is currently hard-coded with an English prefix `Show all {taxonomy label}`. The problem is that I mainly code websites in other languages so I need to translate it. I would suggest removing the prefix or surround it with a translation method so that we can translate it ?

Small preview of the issue :
![dropdown](https://user-images.githubusercontent.com/11065509/85931991-aafe8b80-b8c8-11ea-988f-1d0cb76b0390.png)

Best regards.

**Comment by jjgrainger** [comment]
This was resolved in #81 where the taxonomy label is used instead of a non internationalized string
