### ISSUE TITLE
Repeating field?

### ISSUE THREAD

**Issue by strarsis** [jjgrainger/PostTypes#7]
It would be great to have repeating fields or sets of fields supported by this library.

**Comment by jjgrainger** [comment]
I've avoided adding any field functionality for a number of reasons.

The main reason is [Advanced Custom Fields](https://www.advancedcustomfields.com/). The plugin is amazing for handling custom fields and does a far better job of it than I anything I could make to go alongside this class. I highly recommend it!

Thanks, :)
