### ISSUE TITLE
use PostTypes\Taxonomy is missing in Examples

### ISSUE THREAD

**Issue by vito92** [jjgrainger/PostTypes#70]
Hi,
first of all I need to say that this project is awesome! The same holds for your documentation!
I just testet your example today and it seens like a little import for Taxonomies is missing. So I would suggest to change two lines in the README.md and the examples/books.php:
```
// Import PostTypes.
use PostTypes\PostType;
```
to
```
// Import PostTypes and Taxonomies.
use PostTypes\{PostType,Taxonomy};
```
Or am I missing something?

**Comment by jjgrainger** [comment]
Thanks for highlighting, I've updated the docs and README in PR #79 to ensure the namespaces are included
