### ISSUE TITLE
Support PostTypes

### ISSUE THREAD

**Issue by mmjaeger** [jjgrainger/PostTypes#73]
hello
I was wondering whether this plugin is still fully supported or whether development has kind of stopped -  is is still save to use this plugin??

**Comment by mmjaeger** [comment]
I guess not - too bad - I really like this class

**Comment by jjgrainger** [comment]
Hi @mmjaeger 

Thanks for your question and apologies for not getting back sooner.

This project is still maintained and I am looking to make further fixes and improvements in the near future.

I have also updated my notification settings so I will be responding to issues more promptly.

Thanks again!

**Comment by mmjaeger** [comment]
very glad to hear that - love the script
