### ISSUE TITLE
Column sorting is not working for me

### ISSUE THREAD

**Issue by mmjaeger** [jjgrainger/PostTypes#77]
I was wondering whether anybody else has some issues with sorting columns - when clicking on the column that is supposed to sort I get no posts showing up at all - no error message, nothing 

don't really know how to debug this.

hope somebody can help

**Comment by mmjaeger** [comment]
Welcome back - glad you are still here once in a while

I got it to work with the following code/corrections in the PostType.php file:

`   /**
     * Set query to sort custom columns
     * @param  WP_Query $query
     */
    public function sortSortableColumns($query)
    {
        // don't modify the query if we're not in the post type admin
        if (!is_admin() || $query->get('post_type') !== $this->name) {
            return;
        }

        $orderby = $query->get('orderby');

        // if the sorting a custom column
        if ($this->columns()->isSortable($orderby)) {
            // get the custom column options
            $meta = $this->columns()->sortableMeta($orderby);

            // determine type of ordering
            if ( is_string( $meta ) or is_array( $meta ) and !$meta[1]) {
                $meta_key   = is_array( $meta) ? $meta[0] : $meta;
                $meta_value = 'meta_value';
            } else {
                $meta_key   = $meta[0];
                $meta_value = 'meta_value_num';
            }

            // set the custom order
            $query->set( 'meta_key', $meta_key );
            $query->set( 'orderby', $meta_value );
        }
    }`

**Comment by mmjaeger** [comment]
this has not been fixed yet, right or am I missing something??

**Comment by jjgrainger** [comment]
@mmjaeger I've yet to create the latest stable release, however you can pull the latest dev version using composer...

```
composer require jjgrainger/posttypes:dev-master
```
